FROM fedora:44@sha256:64de49837325632232088e59c20518565a9d657095f9f3c2fa6033a42fb1412b
LABEL maintainer="Oleg V. Kozlyuk <elquentaro@gmail.com>"
LABEL repository="https://github.com/DarkWanderer/devcontainers"

ENV CARGO_HOME=/usr/local RUSTUP_HOME=/usr/local
COPY --chmod=644 config.toml /usr/local/config.toml

ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=${USER_UID}

RUN useradd --uid ${USER_UID} -m ${USERNAME} \
    && echo "${USERNAME} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/${USERNAME} \
    && chmod 0440 /etc/sudoers.d/${USERNAME}

RUN dnf update -y && \
    dnf install -y --setopt=install_weak_deps=False \
        ca-certificates \
        chezmoi \
        clang \
        cmake \
        curl \
        dotnet-sdk-9.0 \
        gcc \
        gh \
        git \
        jq \
        lld \
        lldb \
        make \
        mold \
        nodejs \
        npm \
        openssl-devel \
        pkg-config \
        procps-ng \
        protobuf-compiler \
        rustup \
        shadow-utils \
        sudo \
        tini \
        wget \
        which \
    && dnf clean all \
    && rm -rf /var/cache/dnf

RUN rustup-init -y \
    && rustup component add rust-src llvm-tools-preview rust-analyzer clippy rustfmt \
    && cargo install --locked cargo-audit cargo-bump cargo-edit cargo-llvm-cov cargo-sort cargo-outdated clippy-sarif sarif-fmt \
    && rm -rf /usr/local/registry \
    && mkdir -p /usr/local/registry \
    && chmod 777 /usr/local/registry

WORKDIR /workspace

SHELL ["/bin/bash", "-c"]

CMD ["bash"]
