[target.x86_64-unknown-linux-gnu]
linker = "mold"
target-cpu = "x86-64-v2"

[target.x86_64-unknown-linux-musl]
linker = "mold"
target-cpu = "x86-64-v2"

[target.x86_64-unknown-linux-none]
linker = "mold"
target-cpu = "x86-64-v2"
