name: Rust

on:
  push:
    branches:
      - main
    paths:
      - "rust/**"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "rust/**"
      - ".github/workflows/**"
  workflow_dispatch:

env:
  IMAGE_NAME: rust-devcontainer

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build/Push
        uses: docker/build-push-action@v5
        with:
          context: ./rust
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: docker.io/${{ secrets.DOCKER_USERNAME }}/devcontainer:rust
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
